wandb_version: 1

epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.05
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718564763
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      3:
      - 16
      - 23
      4: 3.8.19
      5: 0.17.1
      8:
      - 1
      - 5
      13: darwin-x86_64
